baseurl = "https://jimmysong.io/"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
title = "Jimmy Song" 
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
hello = "Hi,I'm Jimmy"
subtitle = "I can help you building Cloud Native confidence"
logo = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/avatar-icon.png"
favicon = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/favicon.ico"
dateFormat = "January 2, 2006"
commit = false
#rss = true
#comments = true
#sharebutton = true
algolia = "d2134c5a8d250e6d3246594240c45201" # API key
#gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
description = "jimmysong.io"
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/keuc-cncf.jpg"
desc = "KEUC - China Kubernetes End User Conference 2017"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/cloud-computing.jpg"
desc = "Cloud Computing for every one"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/great-wall-01.jpg"
desc = "Cross the Great Wall to the world"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/big-data-1.jpg"
desc = "Big Data for business decision"

[[Params.bigimg]]
src = "https://res.cloudinary.com/jimmysong/image/upload/banners/data-science-1.jpg"
desc = "Data Science for complexity of human society"

#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/big-data-2.jpg"
#desc = "Big Data"

#[[Params.bigimg]]
#src = "https://res.cloudinary.com/jimmysong/image/upload/banners/data-science-2.jpg"
#desc = "Data Science"

[Author]
  name = "Jimmy Song"
 # website = "https://jimmysong.io"
  email = "rootsongjc@gmail.com"
  facebook = "jimmysongio"
 # googleplus = "+jimmysong" # or xxxxxxxxxxxxxxxxxxxxx
  github = "rootsongjc"
  twitter = "jimmysongio"
  linkedin = "jimmysongio"

[[menu.main]]
    identifier = "Articles"
    name = "Articles"
    url = "posts"
    weight = 1

[[menu.main]]
    parent = "Articles"
    name = "Posts"
    url = "posts"
    weight = 1

[[menu.main]]
    parent = "Articles"
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    url = "categories"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "Cloud Native"
    url = "categories/cloud-native"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Docker"
    url = "categories/docker"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Code"
    url = "categories/code"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Architecture"
    url = "categories/architecture"
    weight = 7

[[menu.main]]
    identifier = "Books"
    name = "Books"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Go"
    url = "cloud-native-go"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 2

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "Spark on kubernetes"
    url = "spark-on-k8s"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Awesome Cloud Native"
    url = "awesome-cloud-native"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 5

[[menu.main]]
    parent = "Projects"
    name = "Istio service mesh"
    url = "http://istio.doczh.cn"
    weight = 6

[[menu.main]]
    name = "About"
    url = "about"
    weight = 5
